theme: jekyll-theme-minimal
title: margregorioschurch's homepage
description: Mar.Gregorios Church is situated at the heart of a small village called Thottapuzha, Eraviperoor, Pathanamthitta District, Kerala, India. One of Kerala's oldest ...
